### ISSUE TITLE
Meeting Sept 27th, Small sample test from Professor Song 

### ISSUE THREAD

**Issue by DerrickYLJ** [DerrickYLJ/worst_case_delay#4]
1. _**Issues from last time:**_

- Take a closer look at the results and check CPA results 
- Run the test example from Professor Song:
<img width="728" alt="Screen Shot 2023-09-26 at 11 00 12 PM" src="https://github.com/DerrickYLJ/worst_case_delay/assets/99985904/361d055d-8202-48b3-8c37-4707cae1ebb1">
Sample output from Real Time Analysis Code: 
stream index: 1, worst case delay: 2.0
stream index: 2, worst case delay: 8.0
stream index: 3, worst case delay: 8.0
stream index: 4, worst case delay: 10.0

Actual Result:
<img width="312" alt="Screen Shot 2023-09-26 at 11 18 13 PM" src="https://github.com/DerrickYLJ/worst_case_delay/assets/99985904/7998c051-380a-4cc8-971f-519e38bd4c10">

2. **_Question regarding RTA:_** 

- [x] Does RTA consider the same priority streams in the summation term? Original: all same-priority streams and the stream with the largest execution time will be considered in the calculation. 
- [x] What if S1, S2, S3, S4 have the same priority, if we are going to calculate the worst-case delay of S2, which one will be for maximum, which ones will be considered for summation terms? 
Currently modified approach: 
(1) we don't select any maximums; 
(2) the rest ones are calculated in summation. (There will be multiple blocking at the same time)
Original approach: 
(1) consider the maximum strictly after Si. (e.g. S4)  
(2) Consider summation terms strictly before Si (e.g. S1)

Essentially, select the stream with a lower or equal priority that has the largest execution time as MAXC; and all other streams with higher or equal priorities will be considered in summation terms (excluding the MAXC if it has the same priority).

3. Updated Result for RTA
<img width="1241" alt="Screen Shot 2023-09-27 at 12 55 42 AM" src="https://github.com/DerrickYLJ/worst_case_delay/assets/99985904/e6c95a77-c930-43c1-8541-958ad7246cfd">
Numerical Results:
nc = [401.880, 419.130, 441.970, 311.60, 258.340, 387.890, 457.429, 377.495, 457.429, 246.810, 402.915, 135.070, 321.626]

data_rta = [205.0, 235.0, 408.0, 340.0, 183.0, 205.0, 404.0, 382.0, 618.0, 376.0, 580.0, 223.0, 436.0]
data_fa = [205, 235, 408, 310, 175, 197, 404, 382, 618, 362, 580, 208, 422]
data_cpa_s = [205, 235, 408, 310, 183, 235, 404, 382, 618, 376, 580, 223, 434]
data_cpa_w = [417, 471, 507, 340, 183, 350, 744, 533, 744, 511, 632, 396, 609]

Conclusion: 
RTA has almost the same result as FA due to the observation that the recursive parameter _I_ is normally completed after only one round. In this case, we may say that FA and RTA approaches can be mathematically reduced to each other in this dual switch network, or at least quite similar in terms of calculation process if recursion is not applied.

4. _**Path to Go:**_
- [ ]  Numerical results and further investigation plus explanation behind results 
- [ ] Why there are differences (2 months) 
- [ ]  Refine numerical computations 
- [ ] Starting in November and writing a conference paper 
- [ ] Build up an automation system that uses RTA to compute all types of network connections 

5. _**Logistics:**_ 
Poster Session: [ComSoc](https://ccnc2024.ieee-ccnc.org/authors/call-posters)
WFCS (paper limit 8 pages) + RTNS (long paper 12 pages)

**Comment by song54** [comment]
We have decided during our last meeting to focus on analyzing VL12 for helping to understand where comes the numerical difference between those methods.
By hand I've quickly analysed the possible delays of VL12 by juste applying the formula of RTA without considering the serialization effect and by assuming that all packets have a delay much smaller than their periods.
The result is what we have obtained by using CPA_W. 396).
Now it remains to further verify how w've achieved other results...
The purpose is to trigger further discussions during our next meeting.

[numerical aapplication cpa_w to VL12.pdf](https://github.com/DerrickYLJ/worst_case_delay/files/12792173/numerical.aapplication.cpa_w.to.VL12.pdf)

**Comment by DerrickYLJ** [comment]
The result of VL12 looks similar to those computed from FA and RTA?

**Comment by song54** [comment]
With rta and cpa_s, and considering the serialization effect (similar to Pay Burst Only Once), we effectively obtain 223 microseconds. I also verified it by hand as following:
ES3->SA: 30(VL10)+8(VL5)+14(VL12) = 52
SA-> ES1: 121(VL9)+8(VL2)+8(VL6)+14(VL7)+14(VL12)=165
So ES3->SA->ES1: 52+165 = 217
SA->SB: 8(VL1)+14(VL8)+121(VL11)+14(VL12)=157
SB->ES2: 14(VL12)=14
So ES3->SA->SB->ES2: 52+157+14=223

**Comment by song54** [comment]
However FA provides 208 which is smaller.
@Theo and @DerrickYLJ , could you check how 208 is obtained using FA method?

**Comment by DerrickYLJ** [comment]
I will check that, thanks for feedback!

**Comment by song54** [comment]
> However FA provides 208 which is smaller. @theo and @DerrickYLJ , could you check how 208 is obtained using FA method?

Theo has verified: VL12 response time of 208 was wrong. The right anwser is 223.

By the way, when discussing with Theo, the VL12 WCRT upper bound  of 135.070 microseconds is obviously impossible. In fact, a simple conter-example can be easily found in the path ES3->SWa->SWb->ES2: a VL12 frame can be blocked by a frame from VL11 (121), so to travel through the path, the VL12 frame will have at least: 14+121+14+14=163 which is already higher than 135.070, even without considering the other VLs of higher priority sharing part of the path.
@Ludovic, could you verify it ?

**Comment by LudoInSpace** [comment]
The e2e latency bounds reported by NC tools for V12, destination ES2 are:

Name of algorithm | Author | e2e delay bound (us)
-|-|-
Panco-ELP | Anne Bouillard | 135.070
Panco-PLP | Anne Bouillard | 135.070
DNC-PMOO | DISCO | 352.611
DNC-SFA | DISCO | 518.402
Panco-SFA | Anne Bouillard | 518.406
DNC-TFA |  DISCO | 544.400
Panco-TFA | Anne Bouillard | 136.467
xTFA-TFA | Ludovic Thomas | 242.819
DNC-TMA | DISCO | 352.611

It appears that only Anne Bouillard's tool is below the value you obtain (223us).
Algorithms from the "TFA" family also report a bound on the delay suffered at each output port.

Delay bounds are in us

Link | Output port's name | DNC-TFA | Panco-TFA | xTFA-TFA
-|-|-|-|-
ES3 - > SwitchA | ES3-o0 | 66.539 |  66.539 | 107.618
SwitchA -> SwitchB | SwitchA-o2 | 314.733 |  58.095 |  95.605
SwitchB -> ES2 | SwitchB-o1 |  163.129 | 11.832 | 39.597
Total | Total |  544.401 |  136.466 | 242.820

EDIT:
As you can see, xTFA and Panco report a delay bound inside SwitchA -> SwitchB that strictly less than your counter-example.
I'll investigate this further, as there might be a network-calculus argument behind this.

**Comment by song54** [comment]
To feed our next meeting, here is the first simulation results (by considering the same sending time of all the VL at time 0, without any offset, but only random starting order among VLs of a same source ES).


[first_simulation_of_Rox_Ernst2000.pdf](https://github.com/DerrickYLJ/worst_case_delay/files/12859424/first_simulation_of_Rox_Ernst2000.pdf)

@DerrickYLJ and Theo: You should verify the result for VL1 which is smaller than the simulation one (371us).

**Comment by DerrickYLJ** [comment]
Theo calculated the FA result manually last summer so now I couldn't find the process of how it is calculated anymore. 
However, I have verified my code for both CPA_S and CPA_W. I think how they are computed should be okay since for CPA_S, it has a similar calculation as FA at the beginning. 

The plotting including result for Rox_Ernst and NC-PK:
<img width="1395" alt="Screen Shot 2023-10-11 at 8 59 03 AM" src="https://github.com/DerrickYLJ/worst_case_delay/assets/99985904/39d7d3ea-da94-497e-9d4b-89a33c5a8400">

nc = [401.880, 419.130, 441.970, 311.60, 258.340, 387.890, 457.429, 377.495, 457.429, 246.810, 402.915, 135.070, 321.626]
data_rta_no_assp = [ 219.0, 235.0, 354.0, 332.0, 175.0, 189.0, 404.0, 338.0, 618.0, 376.0, 550.0, 223.0, 436.0]
data_rta = [205.0, 235.0, 408.0, 340.0, 183.0, 205.0, 404.0, 382.0, 618.0, 376.0, 580.0, 223.0, 436.0]
data_fa = [205, 235, 408, 310, 175, 197, 404, 382, 618, 362, 580, 208, 422]
data_cpa_s = [205, 235, 408, 310, 183, 235, 404, 382, 618, 376, 580, 223, 434]
data_cpa_w = [417, 471, 507, 340, 183, 350, 744, 533, 744, 511, 632, 396, 609]
first_simulation_ernst = [371, 401, 401, 293, 58, 128, 467, 415, 453, 112, 415, 126, 150]
NC_PK = [401.911, 420.994, 443.627, 312.160, 266.764, 420.212, 699.366, 507.494, 699.366, 465.147, 620.064, 255.920, 563.543]

**Comment by LudoInSpace** [comment]
Hi all, 
could you add the following dataset to your plot, you can name it NC-PK:

unit is us. Let's discuss this at 3pm.

VL | NC-PK
-|-
1|401.911
2|420.994
3|443.627
4|312.160
5|266.764
6|420.212
7|699.366
8|507.494
9|699.366
10|465.147
11|620.064
12|255.920
13|563.543

**Comment by song54** [comment]
@DerrickYLJ Contrary to what I've said during our last meeting, unfortunately I did not find time to reproduce more simulation traces, neither to verify the existing traces.
I put here the simulation model that I've built using "java modelling tools" https://jmt.sourceforge.net/
I put also the first simulation traces produced two or three weeks ago.
If you have time before next Wednesday, maybe you can take a look on the different traces to verify if the e2e delays are correct or wrong, especially for those VLs having higher simulation delays than the theoretics given by RTA and CPA-S and FA (I see at least VL1, VL2, VL7 and VL8). You can see for example if the e2e delays are consistent with the local delays on their paths.
Otherwise, no worry, we can discuss Wednesday to make clear the next step.
Here is the screenshot of the model:
![Capture d’écran 2023-10-23 à 09 11 40](https://github.com/DerrickYLJ/worst_case_delay/assets/134134158/2750f043-eb0d-4868-9e50-5677591cb4f4)

And simulation traces:

[SWaToES3_VL13_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067274/SWaToES3_VL13_Response.Time.csv)
[SWaToES3_VL9_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067275/SWaToES3_VL9_Response.Time.csv)
[SWaToES3_VL7_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067276/SWaToES3_VL7_Response.Time.csv)
[SWaToES3_VL3_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067277/SWaToES3_VL3_Response.Time.csv)
[SWaToES3_VL11_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067278/SWaToES3_VL11_Response.Time.csv)
[SWaToES3_VL8_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067279/SWaToES3_VL8_Response.Time.csv)
[SWaToES3_VL4_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067280/SWaToES3_VL4_Response.Time.csv)
[SWbToES2_VL12_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067281/SWbToES2_VL12_Response.Time.csv)
[VL13_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067282/VL13_System.Response.Time.csv)
[VL6_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067283/VL6_System.Response.Time.csv)
[VL10_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067284/VL10_System.Response.Time.csv)
[VL5_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067285/VL5_System.Response.Time.csv)
[VL9_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067286/VL9_System.Response.Time.csv)
[VL7_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067287/VL7_System.Response.Time.csv)
[VL3_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067288/VL3_System.Response.Time.csv)
[VL2_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067289/VL2_System.Response.Time.csv)
[VL11_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067290/VL11_System.Response.Time.csv)
[VL8_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067291/VL8_System.Response.Time.csv)
[VL4_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067292/VL4_System.Response.Time.csv)
[SWaToES1_VL6_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067293/SWaToES1_VL6_Response.Time.csv)
[SWaToES1_VL12_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067294/SWaToES1_VL12_Response.Time.csv)
[SWaToES1_VL5_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067295/SWaToES1_VL5_Response.Time.csv)
[SWaToES1_VL9_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067296/SWaToES1_VL9_Response.Time.csv)
[SWaToES1_VL7_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067297/SWaToES1_VL7_Response.Time.csv)
[SWaToES1_VL2_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067298/SWaToES1_VL2_Response.Time.csv)
[SWbToES4_VL10_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067299/SWbToES4_VL10_Response.Time.csv)
[SWbToES4_VL9_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067300/SWbToES4_VL9_Response.Time.csv)
[SWbToES4_VL11_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067301/SWbToES4_VL11_Response.Time.csv)
[SWbToES2_VL11_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067302/SWbToES2_VL11_Response.Time.csv)
[SWbToES2_VL8_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067303/SWbToES2_VL8_Response.Time.csv)
[SWbToSWa_VL13_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067304/SWbToSWa_VL13_Response.Time.csv)
[SWbToSWa_VL6_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067305/SWbToSWa_VL6_Response.Time.csv)
[SWbToSWa_VL9_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067306/SWbToSWa_VL9_Response.Time.csv)
[SWbToSWa_VL7_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067308/SWbToSWa_VL7_Response.Time.csv)
[SWbToSWa_VL3_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067309/SWbToSWa_VL3_Response.Time.csv)
[SWbToSWa_VL2_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067310/SWbToSWa_VL2_Response.Time.csv)
[SWaToSWb_VL12_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067311/SWaToSWb_VL12_Response.Time.csv)
[SWaToSWb_VL10_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067312/SWaToSWb_VL10_Response.Time.csv)
[SWaToSWb_VL11_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067313/SWaToSWb_VL11_Response.Time.csv)
[SWaToSWb_VL8_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067314/SWaToSWb_VL8_Response.Time.csv)
[ES4toSWb_VL13_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067315/ES4toSWb_VL13_Response.Time.csv)
[ES4toSWb_VL6_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067316/ES4toSWb_VL6_Response.Time.csv)
[ES3toSWa_VL12_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067317/ES3toSWa_VL12_Response.Time.csv)
[ES3toSWa_VL10_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067318/ES3toSWa_VL10_Response.Time.csv)
[ES2toSWb_VL9_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067319/ES2toSWb_VL9_Response.Time.csv)
[ES2toSWb_VL7_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067320/ES2toSWb_VL7_Response.Time.csv)
[ES2toSWb_VL3_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067321/ES2toSWb_VL3_Response.Time.csv)
[ES2toSWb_VL2_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067322/ES2toSWb_VL2_Response.Time.csv)
[ES1toSWa_VL11_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067323/ES1toSWa_VL11_Response.Time.csv)
[ES1toSWa_VL8_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067324/ES1toSWa_VL8_Response.Time.csv)
[ES1toSWa_VL4_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067325/ES1toSWa_VL4_Response.Time.csv)
[SWbToES2_VL1_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067326/SWbToES2_VL1_Response.Time.csv)
[SWaToSWb_VL1_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067327/SWaToSWb_VL1_Response.Time.csv)
[VL1_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067328/VL1_System.Response.Time.csv)
[ES1toSWa_VL1_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067329/ES1toSWa_VL1_Response.Time.csv)
[ES3toSWa_VL5_Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067330/ES3toSWa_VL5_Response.Time.csv)

**Comment by song54** [comment]
Thre is also an elder trace of VL12 (I've to figure out why later):
[VL12_System Response Time.csv](https://github.com/DerrickYLJ/worst_case_delay/files/13067433/VL12_System.Response.Time.csv)
